site_name: Mobexler Usage Guide 

nav:
    - Home : index.md
    - Tools : Awesome_tools.md
    - Setup : setup.md
    - Releases : release.md
    - License & Disclaimer: license.md
    - Download : download.md
    - Credits : credits.md
    - Learn Mobile Security: training.md
    
theme : 
        name: simplex
